add 0.2.1-patch-3 to changelog (#264)

diff --git a/.github/workflows/e2e.yaml b/.github/workflows/e2e.yaml
--- a/.github/workflows/e2e.yaml
+++ b/.github/workflows/e2e.yaml
@@ -67,7 +67,8 @@ jobs:
         ref: ${{ inputs.checkout_ref }}
     
     - if: ${{ !(needs.test.status == 'success')}}
-      run: exit 1 # will make status show as failure
+      run: |
+        exit 1 # will make status show as failure
 
     - if: always()
       uses: ./.github/actions/end-status
