api change

diff --git a/.github/workflows/e2e.yaml b/.github/workflows/e2e.yaml
--- a/.github/workflows/e2e.yaml
+++ b/.github/workflows/e2e.yaml
@@ -66,8 +66,10 @@ jobs:
       with:
         ref: ${{ inputs.checkout_ref }}
     
-    - if: ${{ !(needs.test.status == 'success')}}
-      run: exit 1 # will make status show as failure
+    - if: ${{ !(needs.test.conclusion == 'success')}}
+      run: |
+        echo "job status: ${{ needs.test.conclusion }}"
+        exit 1 # will make status show as failure
 
     - if: always()
       uses: ./.github/actions/end-status
